In [1]:
import surrogate_model
import argparse
import numpy as np
import pandas as pd
import src.dynamic_pipeline as dynamic_pipeline

/opt/conda/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
df = pd.read_csv('./data/concrete.csv')
# df = dynamic_pipeline.preprocess_dynamic(df)

In [3]:
ret_dict = dynamic_pipeline.preprocess_dynamic(df)

제거된 컬럼이 없습니다.
cement: 비대칭 분포로 확인됨. IQR 방식 적용.
slag: 비대칭 분포로 확인됨. IQR 방식 적용.
ash: 비대칭 분포로 확인됨. IQR 방식 적용.
water: 비대칭 분포로 확인됨. IQR 방식 적용.
superplastic: 비대칭 분포로 확인됨. IQR 방식 적용.
coarseagg: 비대칭 분포로 확인됨. IQR 방식 적용.
fineagg: 비대칭 분포로 확인됨. IQR 방식 적용.
age: 비대칭 분포로 확인됨. IQR 방식 적용.
strength: 비대칭 분포로 확인됨. IQR 방식 적용.
cement: 값 범위 중요 → MinMaxScaler 적용
slag: 값 범위 중요 → MinMaxScaler 적용
ash: 값 범위 중요 → MinMaxScaler 적용
water: 값 범위 중요 → MinMaxScaler 적용
superplastic: 값 범위 중요 → MinMaxScaler 적용
coarseagg: 값 범위 중요 → MinMaxScaler 적용
fineagg: 값 범위 중요 → MinMaxScaler 적용
age: 비대칭 분포 → RobustScaler 적용
strength: 값 범위 중요 → MinMaxScaler 적용


In [4]:
ret_dict['processed_df'].to_csv('./data/temp.csv', index=False)

In [5]:
# args = argparse.Namespace(
#     target = ['strength'],
#     data_path='./data/temp.csv',
#     model='catboost',
#     prj_id = 40,
#     seed=40
# )
# surrogate_model.main(args, ret_dict['scalers'])

In [6]:
args = argparse.Namespace(
    target = ['strength'],
    data_path='./data/temp.csv',
    model='tabpfn',
    prj_id = 40,
    seed=40
)
surrogate_model.main(args, ret_dict['scalers'])

2025-02-02 23:45:05,876 - INFO - X_train.shape: (740, 8)
2025-02-02 23:45:05,877 - INFO - X_test.shape: (186, 8)
2025-02-02 23:45:05,877 - INFO - y_train.shape: (740, 1)
2025-02-02 23:45:05,878 - INFO - y_test.shape: (186, 1)
/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(186, 1)
(186, 1)
       rmse       mae        r2
0  0.056226  0.032977  0.926711
(186, 1) (186, 1)
(186, 1)


In [7]:
import os

In [8]:
os.listdir('./prj/40/surrogate_model')

['importance.csv', 'eval.csv', 'surrogate_model.csv', 'model.cbm', 'model.pkl']

In [9]:
import search_model

In [10]:
controll_range = df.drop(columns=['strength']).columns.tolist()
controll_range = {col: (df[col].min(), df[col].max()) for col in controll_range}


In [11]:
controll_range

{'cement': (102.0, 540.0),
 'slag': (0.0, 359.4),
 'ash': (0.0, 200.1),
 'water': (121.8, 247.0),
 'superplastic': (0.0, 32.2),
 'coarseagg': (801.0, 1145.0),
 'fineagg': (594.0, 992.6),
 'age': (1, 365)}

In [12]:
print(df['strength'].min(),'~',df['strength'].max())

2.33 ~ 82.6


In [13]:
from src.datasets.data_loader import load_data

In [14]:
df_scaled = load_data(args.data_path)
X = df_scaled.drop(columns=args.target)
y = df_scaled[args.target]
x_col_list = X.columns.tolist()

X_train,y_train = X.to_numpy(),y.to_numpy()


In [15]:
scalers = ret_dict['scalers']

In [16]:
# user_req = scalers['strength'].transform(np.array(args.user_request_target[0]).reshape(-1,1))

In [17]:
ur = []
ur.append(np.array(40.0).reshape(-1,1)[0])
ur = np.array(ur)

In [18]:
ur

array([[40.]])

In [19]:
x,y = search_model.find_top_k_similar_with_user_request(ur,X_train,y_train,k=50)

In [20]:
x.shape
y.shape


(50, 1)

In [21]:
from src.datasets.data_loader import load_data

In [22]:
args = argparse.Namespace(
    model='catboost',
    search_model='k_means',
    data_path='./data/temp.csv',
    controll_name=['cement', 'slag', 'ash', 'water', 'superplastic', 'coarseagg', 'fineagg', 'age'],
    controll_range= controll_range,
    target=['strength'],
    importance={'cement': 1,
                'water': 2,
    },
    optimize={'cement': 'minimize',
                'water': 'minimize',
    },
    prj_id=40,
    seed=40,
    user_request_target=[40.0]
)

In [23]:
# %%time 
x_opt = search_model.main(args,ret_dict['scalers'])

/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/utils/valida

x_min :  [ 0.          0.          0.         -0.05148515  0.          0.
 -0.03235294 -1.28571429]
x_max :  [ 1.          1.05057001  1.          1.18811881  1.45701357  1.
  1.14       16.04761905]


0it [00:00, ?it/s]WARNING clustering 2000 points to 666 centroids: please provide at least 25974 training points
WARNING clustering 2000 points to 666 centroids: please provide at least 25974 training points
WARNING clustering 2000 points to 666 centroids: please provide at least 25974 training points
WARNING clustering 2000 points to 666 centroids: please provide at least 25974 training points
WARNING clustering 2000 points to 666 centroids: please provide at least 25974 training points
WARNING clustering 2000 points to 666 centroids: please provide at least 25974 training points
WARNING clustering 2000 points to 666 centroids: please provide at least 25974 training points
WARNING clustering 2000 points to 666 centroids: please provide at least 25974 training points
WARNING clustering 2000 points to 666 centroids: please provide at least 25974 training points
WARNING clustering 2000 points to 666 centroids: please provide at least 25974 training points
WARNING clustering 2000 points t

(50, 8)
search model 소요 시간: 469.3105초
CPU times: user 49min 58s, sys: 3min 24s, total: 53min 23s
Wall time: 7min 49s


In [26]:
scalers['cement'].inverse_transform(np.array(40.0).reshape(-1,1))[0]

array([17622.])

In [29]:
total_opt = []
for i in x_opt:
    opt = []
    for j in range(len(i)):
        opt.append(scalers[x_col_list[j]].inverse_transform(i[j].reshape(-1,1))[0])
    print(np.array(opt))
    total_opt.append(np.array(opt))

[[ 486.06310502]
 [ 124.32334134]
 [  99.28333238]
 [ 221.32781185]
 [  19.93384892]
 [1069.34986955]
 [ 955.0513099 ]
 [ 138.79179351]]
[[ 325.89650467]
 [  86.3179305 ]
 [  92.30539794]
 [ 190.92074381]
 [  28.40046049]
 [1117.80784507]
 [ 736.15160251]
 [ 241.25521982]]
[[ 258.17744378]
 [ 154.09622515]
 [ 139.85217533]
 [ 214.49866224]
 [  13.44225322]
 [1119.59138071]
 [ 859.03301819]
 [ 290.99187145]]
[[ 239.52926128]
 [ 151.41072184]
 [ 110.52231771]
 [ 199.87454173]
 [  14.1404658 ]
 [1063.68194169]
 [ 885.83351232]
 [ 125.43357969]]
[[336.26081903]
 [235.94315704]
 [176.28921152]
 [187.98178469]
 [ 13.52060783]
 [999.79804918]
 [992.6       ]
 [179.8664346 ]]
[[ 157.89767601]
 [  86.2320664 ]
 [  78.89415053]
 [ 175.47901277]
 [  15.08133198]
 [1011.4161707 ]
 [ 596.45872141]
 [ 360.96439738]]
[[ 102.        ]
 [  76.80511047]
 [ 114.96380204]
 [ 158.48831309]
 [  29.90650122]
 [1045.05031042]
 [ 659.22422329]
 [ 324.99412631]]
[[253.22075598]
 [279.92833815]
 [ 77.57351827]
 

In [35]:
total_opt = np.array(total_opt).squeeze()

In [37]:
total_opt[0]

array([ 486.06310502,  124.32334134,   99.28333238,  221.32781185,
         19.93384892, 1069.34986955,  955.0513099 ,  138.79179351])